version: "3"

volumes:
  blue-volume:
    driver: local
  red-volume:
    driver: local

services:
  red-mongo:
    container_name: red-mongo
    image: docker.io/bitnami/mongodb:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=example
      - MONGODB_DATABASE=red
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"
    volumes:
      - "red-volume:/bitnami/mongodb"
  mysql:
    platform: linux/amd64
    image: mysql:8.0.31
    container_name: blue-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: blue
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - blue-volume:/var/lib/mysql
